Repository Nuitka/Nuitka, pull requests merged in 2020-04, with the labels that each got.

#665 Add OpenBSD to clang and posix platforms.
  nuitka/build/SingleExe.scons
  nuitka/freezer/Standalone.py
Labels: enhancement

#687 Fix to not have KeyError: 'style' when building
  nuitka/Tracing.py
  nuitka/freezer/BytecodeModuleFreezer.py
Labels: bug, develop

#685 Fix issue with warning in getPEFileInformation
  nuitka/utils/SharedLibraries.py
Labels: bug

#678 Remove assertion of exist status 0 in favor of check_call
  nuitka/tools/release/Documentation.py
  nuitka/utils/Execution.py
Labels: enhancement
